server:
  port: 25566

logging:
  level:
    com.lhl.minecraft_chat: warn

cors:
  # 允许哪些源访问
  allowed-origins: http://localhost:5173/, http://localhost:4173/

# 日志文件
log-file:
  # 路径
  path: D:/logs
  # 返回哪些类型日志，可选：PLAYER-CHAT-MSG, PLAYER-LOGINOUT-MSG, RAW-INFO-LOG, RAW-WARN-LOG
  filter: PLAYER-CHAT-MSG, PLAYER-LOGINOUT-MSG